/**
 * @author Sumanth Dathathri
 * @author Nikos Arechiga
 * Toyota InfoTechnology Center, USA
 * 465 N Bernardo Ave, Mountain View, CA 94043
 */

package dl.logicsolvers.z3kit;

//import proteus.logicsolvers.abstractions.*;
import interfaces.text.TextOutput;

import java.util.*;

import dl.semantics.*;
import dl.syntax.*;

import java.io.*;

import dl.logicsolvers.abstractions.LogicSolverInterface;
import dl.logicsolvers.abstractions.LogicSolverResult;


public class z3Interface extends LogicSolverInterface {

	public boolean debug = false;

	public void setPrecision( double precision ) {
	}

//Constructors
	// Constructor with default precision
	public z3Interface() {

		// Generate the workspace
		File z3workspacedir = new File("z3workspace");
                if (!z3workspacedir.exists()) {
                        z3workspacedir.mkdir();
                }
	}

// "checkValidity" family of methods -- try to find a counterexample
	public LogicSolverResult checkValidity( String filename, dLFormula thisFormula, String comment ) throws Exception {
		TextOutput.debug("Entering checkValidity( string, dlformula, string) ");
		dLFormula negatedFormula = thisFormula.negate();
		ArrayList<dLFormula> theseFormulas = negatedFormula.splitOnAnds();

		// Try to find a counterexample
		//LogicSolverResult subResult = findInstance( filename, theseFormulas, comment );
		LogicSolverResult subResult = findInstance( theseFormulas);

		//TextOutput.debug(subResult);
		// We queried the negation, so invert the result
		LogicSolverResult result;
		if ( subResult.satisfiability.equals("unsat") ) {
			result = new LogicSolverResult("sat", "valid", new Valuation() );
			TextOutput.debug("Your formula is valid");
		} else if ( subResult.satisfiability.equals("sat") ) { 
			// The valuation is then a counterexample
			// but with z3 we can't be sure
			result = new LogicSolverResult("unknown", "unknown", subResult.valuation );
		} else {
			//gibberish, I guess
			result = new LogicSolverResult("unknown", "unknown", new Valuation() );
		}
		TextOutput.debug("Returning.");
		return result;
	}

// "FindInstance" family of methods
	public LogicSolverResult findInstance( String filename, List<dLFormula> theseFormulas, String comment )
					throws Exception {
		TextOutput.debug("Entering findInstance( String, dLformula, String )");
		File queryFile = writeQueryFile( filename, theseFormulas, comment );
		TextOutput.debug("Running query on file: " + filename);
		//TextOutput.debug(runQuery(queryFile));
		return runQuery( queryFile );
	}

// Automatically comment a list of formulas
	protected String generateFindInstanceComment( List<dLFormula> theseFormulas ) {
		String comment = ";; Find a valuation of variables that satisfies the formulas:\n;;\n";
		Iterator<dLFormula> formulaIterator = theseFormulas.iterator();
		int counter = 1;
		while ( formulaIterator.hasNext() ) {
			comment = comment + "\n;; Formula " + counter + ":\n";
			comment = comment + ";; " + formulaIterator.next().toMathematicaString();
			counter = counter + 1;
		}

		return comment;
	}

	protected String generateCheckValidityComment( List<dLFormula> theseFormulas ) {
		String comment = ";; Check (conjunctive) validity of: \n;;\n";
		Iterator<dLFormula> formulaIterator = theseFormulas.iterator();
		int counter = 1;
		while ( formulaIterator.hasNext() ) {
			comment = comment + ";; Formula " + counter + ":\n";
			comment = comment + ";; " + formulaIterator.next().toMathematicaString();
			counter = counter + 1;
		}

		return comment;
	}

	public String timeStampComment( String comment ) {
		Date date = new Date();
		String stampedComment = ";; Automatically generated by Proteus on " + date.toString() + "\n\n";
		stampedComment = stampedComment + comment;
		
		return stampedComment;
	}

	public String commentLine( String comment ) {
		return ";; " + comment + "\n";
	}
	

// Runs z3 on a query file, written by some other function The point of this function is to allow code reuse of 
// the piece that actually invokes z3
	protected LogicSolverResult runQuery( File queryFile ) throws Exception {
		TextOutput.debug("Entering runQuery( File )");
		LogicSolverResult result = null;

		//String precisionArgument = "--precision " + precision;
//		ProcessBuilder queryPB = new ProcessBuilder("z3", "--model", 
//								precisionArgument, queryFile.getAbsolutePath() );
		ProcessBuilder queryPB = new ProcessBuilder("z3", queryFile.getAbsolutePath() );
		TextOutput.debug( "Commmand is: " + queryPB.command() );
		queryPB.redirectErrorStream( true );
		Process queryProcess = queryPB.start();
		BufferedReader z3Says = new BufferedReader( new InputStreamReader(queryProcess.getInputStream()) );

		String line;
		String totalOutput = "";
		while ( (line = z3Says.readLine()) != null ) {
			totalOutput += line;
			if ( line.contains("unsat")) {
				
			}
			//TextOutput.debug( line );
			/*
			if ( line.contains("unsat")) {
				result = new LogicSolverResult( "unsat", "notvalid", new Valuation() );
			} else if ( line.contains("delta-sat") ) {
				Valuation cex = extractModel( new File( queryFile.getAbsolutePath() + ".model") );
				result = new LogicSolverResult( "delta-sat", "unknown", cex );
			} else if ( line.equals("unknown") ) {
				result = new LogicSolverResult( "unknown", "unknown", new Valuation() );
			}
			*/
//			} else {
//				throw new Exception( line );
//			}
		}// else {
//			throw new Exception("z3 returned no output!");
//		}
		//TextOutput.debug("Solver result is: ");
		//TextOutput.debug( result.toString() );
		if ( result == null ) {
			throw new RuntimeException("z3 returned unexpected output:" + totalOutput );
		}

		//queryFile.delete();
		return result;
	}

// Extracts a counterexample from a *.model file produced after running z3
	
	public String decorateFilename( String base ) {
		double randomID = Math.round(Math.random());
		Date date = new Date();
		return "z3workspace/" + base + + date.getTime() + "." + randomID + ".smt2";
	}

//
	public String generateFilename() {
		double randomID = Math.round(Math.random());
		Date date = new Date();
		return "z3workspace/query." + date.getTime() + "." + randomID + ".smt2";
	}

// Writes a query file for a logical formula.  Note that it does not negate the formula, it just writes out
// a satisfiability query for the formula that it is given
	protected File writeQueryFile( String filename, List<dLFormula> theseFormulas, String comment ) 
			throws Exception {
		//String queryString = "(set-logic QF_NRA)\n\n";
		String queryString="";
		
		// First extract the list of all the variables that occur in any of the formulas
		Iterator<dLFormula> formulaIterator = theseFormulas.iterator();
		Set<RealVariable> variables = new HashSet<RealVariable>();
		while ( formulaIterator.hasNext() ) {
			variables.addAll( formulaIterator.next().getFreeVariables() );
		}

		// Now print the variable declarations
		queryString = queryString + "\n;; Variable declarations\n";
		//RealVariable thisVariable;
		Iterator<RealVariable> variableIterator = variables.iterator();
		while ( variableIterator.hasNext() ) {
			queryString = queryString + "(declare-const " + variableIterator.next() + "  Real )\n";
		}

		// Assert each formula
		formulaIterator = theseFormulas.iterator();
		dLFormula thisFormula;
		while ( formulaIterator.hasNext() ) {
			thisFormula = formulaIterator.next();
			if( debug ) {
				if ( thisFormula == null ) {
					TextOutput.debug("Got a null formula!");
				} else {
					TextOutput.debug("Currently printing out formula: " 
						+ thisFormula.toMathematicaString() );
				}
			}

			queryString = queryString + "\n;; Formula is (" + thisFormula.toMathematicaString() +")\n";
			queryString = queryString + "(assert " + thisFormula.todRealString() + " )\n";

		}

		// Print the little thing that needs to go at the end
		queryString = queryString + "\n(check-sat)\n (get-model)\n";

		// Now generate the actual file
		PrintWriter queryFile = new PrintWriter( filename );
		queryFile.println( timeStampComment( comment ) + "\n" );
		queryFile.println( queryString );
		queryFile.close();
		if( debug ) {
			TextOutput.debug("Done writing file, writeQueryFile is returning");
		}
		return new File( filename );

	}

}

